envVars:
      - key: DB_URL
        value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - key: DB_HOST
        fromDatabase:
          name: meu-db-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: meu-db-postgres
          property: port
      - key: DB_NAME
        fromDatabase:
          name: meu-db-postgres
          property: database
      - key: DB_USER
        fromDatabase:
          name: meu-db-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: meu-db-postgres
          property: password